config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'

end

app/models/article.rb
class Article < ActiveRecord::Base
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  def index
    @articles = Article.last(3)
  end

  def contact
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  private
  
  def sign_up_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :username,
      :firstname,
      :lastname
)
 end
   
  def account_update_params
    params.require(:user).permit(
       :email,
       :password,
       :password_confirmation,
       :current_password,
       :username,
       :firstname,
       :lastname
)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Creado Por</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.user.username %></td>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creado Por:</strong>
  <%= @article.user.username %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_foot.html.erb
<% if current_user %>
<footer class="footer-distributed">
	<div class="footer-right">
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>
	</div>
	<div class="footer-left">
		<p class="footer-links">
			·
			<a class="page-scroll" href="#portfolio">Contact Us</a>
			·
			<a class="page-scroll" href="#services">About Us</a>
			·
		</p>
		<p> </p>
	</div>
</footer>

<% else %>

<footer class="footer-distributed">

			<div class="footer-left">

				<h3>Fucking<span>Footer</span></h3>

				<p class="footer-links">
					<a href="https://rexrowan.github.io/HandyCraft/">Home</a>
					·
					<a href="#">Blog</a>
					·
					<a href="#">Pricing</a>
					·
					<a href="#">About</a>
					·
					<a href="#">Faq</a>
					·
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">Super.Ting © 2015</p>

				<div class="footer-icons">

					<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
					<a href="https://twitter.com/MeanMachineRex"><i class="fa fa-twitter"></i></a>
					<a href="https://uk.linkedin.com/in/huskychief"><i class="fa fa-linkedin"></i></a>
					<a href="https://github.com/RexRowan"><i class="fa fa-github"></i></a>

				</div>

			</div>

			<div class="footer-right">

				<p>Contact Us</p>

				<form action="#" method="post">

					<input type="text" name="email" placeholder="Email">
					<textarea name="message" placeholder="Message"></textarea>
					<button>Send</button>

				</form>

			</div>

		</footer>
		
		<% end %>
		

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fucking Rotten", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Contáctanos", pages_contact_path %></li>
        <li><%= link_to "Sobre Nosotros", pages_about_path %></li>
        <li><%= link_to "Crear un Artículo", new_article_path %></li>
        
        
        <% if !current_user %>
        
        <li><%= link_to "Registrarse", new_user_registration_path %></li>
        <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
       
       <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><%= link_to "Editar Mi Perfil", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
             <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fucking Rotten</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/nav' %>
<%= bootstrap_flash %>
<div class='container'>
  <%= yield %>
</div>

  <%= render 'layouts/foot' %>
</body>
</html>

app/views/pages/about.html.erb
   <div class="row">
 <div class="col-lg-12 text-center">
 <h1>About Us</h1>
 <p class="lead">Test Text</p>
 <ul class="list-unstyled">
 <li>List Item</li>
 <li>List Item 2</li>
 </ul>
 </div>
	</div>

app/views/pages/contact.html.erb
<div class="row">
	<div class="col-lg-12 text-center">
		<h1>Contact Us</h1>
		<p class="lead">Test Text</p>
		<ul class="list-unstyled">
			<li>List Item</li>
			<li>List Item 2</li>
		</ul>
	</div>
</div>

app/views/pages/index.html.erb
<!--Index Page-->
<div class="row">
	<!-- Blog Post Content Column -->
	<div class="col-lg-8">
		<!-- Blog Post -->
		<!-- Title -->
		<h1>Blog Post Title</h1>


		<!-- Author -->
		<p class="lead">
			by <a href="#">Start Bootstrap</a>
		</p>
		<hr>
		<!-- Date/Time -->
		<p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
		<hr>
		<!-- Preview Image -->
		<img class="img-responsive" src="http://placehold.it/900x300" alt="">
		<hr>
		<!-- Post Content -->
		<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
			obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
			eos magni recusandae laborum minus inventore?</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
				quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
				Temporibus, voluptatibus.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
					blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
					perspiciatis. Enim, iure!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
						placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
						obcaecati?</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
							aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
							recusandae? Qui, necessitatibus, est!</p>
							<hr>
							<!-- Blog Comments -->
							<!-- Comments Form -->
							<div class="well">
								<h4>Leave a Comment:</h4>
								<form role="form">
									<div class="form-group">
										<textarea class="form-control" rows="3"></textarea>
									</div>
									<button type="submit" class="btn btn-primary">Submit</button>
								</form>
							</div>
							<hr>

							<!-- Posted Comments -->
							<!-- Comment -->
							<div class="media">
								<a class="pull-left" href="#">
									<img class="media-object" src="http://placehold.it/64x64" alt="">
								</a>
								<div class="media-body">
									<h4 class="media-heading">Start Bootstrap
										<small>August 25, 2014 at 9:30 PM</small>
									</h4>
									Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
									commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
									ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
								</div>
							</div>
							<!-- Comment -->
							<div class="media">
								<a class="pull-left" href="#">
									<img class="media-object" src="http://placehold.it/64x64" alt="">
								</a>
								<div class="media-body">
									<h4 class="media-heading">Start Bootstrap
										<small>August 25, 2014 at 9:30 PM</small>
									</h4>
									Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
									commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
									ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
									<!-- Nested Comment -->
									<div class="media">
										<a class="pull-left" href="#">
											<img class="media-object" src="http://placehold.it/64x64" alt="">
										</a>
										<div class="media-body">
											<h4 class="media-heading">Nested Start Bootstrap
												<small>August 25, 2014 at 9:30 PM</small>
											</h4>
											Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
											commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
											ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
										</div>
									</div>
									<!-- End Nested Comment -->
								</div>
							</div>
						</div>

						<!-- Blog Sidebar Widgets Column -->
						<div class="col-md-4">
							<!-- Blog Search Well -->
							<div class="well">
								<h4>Blog Search</h4>
								<div class="input-group">
									<input type="text" class="form-control">
									<span class="input-group-btn">
										<button class="btn btn-default" type="button">
											<span class="glyphicon glyphicon-search"></span>
										</button>
									</span>
								</div>
								<!-- /.input-group -->
							</div>
							<!-- Blog Categories Well -->
							<div class="well">
								<h4>Blog Categories</h4>
								<div class="row">
									<div class="col-lg-6">
										<ul class="list-unstyled">
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
										</ul>
									</div>
									<div class="col-lg-6">
										<ul class="list-unstyled">
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
											<li><a href="#">Category Name</a>
											</li>
										</ul>
									</div>
								</div>
								<!-- /.row -->
							</div>
							<!-- Side Widget Well -->

							<div class="well"> 
								<h4>Post Recientes</h4>
								<% @articles.each do |a| %>
								Creado por: <%= a.user.username %><br />
								<strong><%= link_to a.title, a %></strong>
								<p><%= truncate(a.body) %></p>
								<% end %>
								
								</div>
							</div>
						</div>
						<!-- /.row -->
						<hr>